### ISSUE TITLE
#token method confusion

### ISSUE THREAD

**Issue by servel333** [cayasso/access-token#1]
I am confused by this line in the readme document:

```
var token = accessToken.token(token);
```

It appears that the parameter taken by `#token` is a variable `token` but this variable is defined on the very same line that it is used. In other words, it appears that `token` will always be undefined in this context. Is there any difference between the above code and this?

```
var token = accessToken.token();
```

And, what exactly is the `#token` method expecting to take as a parameter?

**Comment by cayasso** [comment]
@servel333 Sorry for the confusion, y just updated the docs on that and also here you will find how a `myToken` should look like https://github.com/cayasso/access-token#api
Thanks!

**Comment by servel333** [comment]
Ahh, I see now. `myToken` (formally `token`) is defined after the initial usage example and I couldn't figure out where it came from. Thanks for the clarification.

**Comment by cayasso** [comment]
:+1:
